image: promact/docker-dotnet-nodejs:latest
stages:
  - build
  - test
before_script:
  - "dotnet restore"
build:
  stage: build
  script:
    - "dotnet build"
test:
  stage: test
  script:
    - "dotnet test"
